name: VUE CLI Lint

on:
  push:
    branches: [ develop ]
    paths:
      - 'l2-frontend/**'
  pull_request:
    branches: [ develop ]

jobs:
  webpack_build_prod:

    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'l2-frontend/yarn.lock'

      - name: Install Dependencies
        run: make npm_install_cached

      - name: Running linter
        run: make ci_lint
